# Generated by Django 5.2.7 on 2025-10-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('id_proof', models.FileField(upload_to='id_proofs/')),
            ],
        ),
    ]
