# Generated by Django 5.2.7 on 2025-12-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='barangay',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
