# Generated by Django 5.2.7 on 2025-11-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id_proof',
        ),
        migrations.AddField(
            model_name='registration',
            name='id_proof_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
