# Generated by Django 5.2.9 on 2025-12-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_notification_notification_type_reliefrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reliefrequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='reliefrequest',
            name='notes',
            field=models.TextField(default='', help_text='Additional notes or reason for requesting relief'),
        ),
        migrations.AddField(
            model_name='reliefrequest',
            name='relief_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Medicine', 'Medicine'), ('Hygiene', 'Hygiene'), ('Shelter', 'Shelter'), ('Others', 'Others')], default='Food', max_length=20),
        ),
    ]
