# Generated by Django 5.2.9 on 2025-12-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_reliefrequest_reason_reliefrequest_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliefrequest',
            name='relief_given',
            field=models.BooleanField(default=False, help_text='Whether the relief has been physically given to the user'),
        ),
    ]
