# Generated by Django 5.2.8 on 2025-12-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_adminlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='barangay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
