# Generated by Django 5.2.8 on 2025-12-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_registration_barangay_registration_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('relief_type', models.CharField(max_length=100)),
                ('date_given', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('given', 'Given'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_given'],
            },
        ),
    ]
